<<<<<<< HEAD
# Generated by Django 2.1.5 on 2020-03-24 14:26
=======
# Generated by Django 3.0.2 on 2020-03-23 17:52
>>>>>>> 4a5faa6c05674a9571542183d03e73dc7327a434

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('details', '0001_initial'),
=======
        ('details', '__first__'),
>>>>>>> 4a5faa6c05674a9571542183d03e73dc7327a434
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(default='My Wishlist', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(blank=True, to='details.Book')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
