# Generated by Django 3.0.2 on 2020-02-14 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20200214_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
