# Generated by Django 3.0.2 on 2020-03-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20200301_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
