# Generated by Django 3.0.2 on 2020-03-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_remove_book_avg_rating'),
        ('wishlist', '0007_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='books',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='details.Book'),
        ),
    ]
