# Generated by Django 3.0.2 on 2020-03-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_remove_book_avg_rating'),
        ('wishlist', '0009_auto_20200302_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(blank=True, to='details.Book'),
        ),
    ]
