# Generated by Django 3.0.2 on 2020-02-11 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_delete_rating'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='details.Book'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
