# Generated by Django 2.1.5 on 2020-01-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('condition', models.CharField(blank=True, choices=[('N', 'New'), ('U', 'Used')], max_length=1)),
                ('type', models.CharField(choices=[('H', 'Hardback'), ('P', 'Paperback')], max_length=1)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
