# Generated by Django 2.1.5 on 2020-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
