# Generated by Django 2.1.5 on 2020-02-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200202_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='picture',
            new_name='cover',
        ),
    ]
