# Generated by Django 2.1.5 on 2020-02-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20200202_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(height_field=50, upload_to='uploads/', width_field=50),
        ),
    ]
