# Generated by Django 3.0.2 on 2020-02-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20200202_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5),
            preserve_default=False,
        ),
    ]
