# Generated by Django 2.1.5 on 2020-02-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20200202_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
