# Generated by Django 3.0.2 on 2020-02-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_book_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='cost',
        ),
    ]
