# Generated by Django 2.1.5 on 2020-02-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_auto_20200204_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('U', 'Used')], max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('H', 'Hardback'), ('P', 'Paperback')], max_length=1),
        ),
    ]
