# Generated by Django 2.1.5 on 2020-02-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_auto_20200204_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Hardback', 'Hardback'), ('Paperback', 'Paperback')], max_length=10),
        ),
    ]
