# Generated by Django 3.0.2 on 2020-02-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_auto_20200203_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cost',
            new_name='price',
        ),
    ]
