# Generated by Django 2.1.5 on 2020-02-20 01:57

import details.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_auto_20200214_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, verbose_name=details.models.Author),
        ),
    ]
