# Generated by Django 2.1.5 on 2020-03-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0014_auto_20200220_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
