# Generated by Django 2.1.5 on 2020-03-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_book_avg_rating'),
        ('details', '0014_auto_20200220_0157'),
    ]

    operations = [
    ]
