# Generated by Django 3.0.3 on 2020-03-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0014_auto_20200220_0157'),
        ('details', '0013_book_avg_rating'),
    ]

    operations = [
    ]
