# Generated by Django 3.0.2 on 2020-02-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_auto_20200203_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
