# Generated by Django 3.0.2 on 2020-03-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_merge_20200301_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='avg_rating',
        ),
    ]
