# Generated by Django 3.0.2 on 2020-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_remove_book_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='slugtest'),
            preserve_default=False,
        ),
    ]
