# Generated by Django 3.0.2 on 2020-03-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0017_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=300),
        ),
    ]
