# Generated by Django 3.0.2 on 2020-02-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0019_auto_20200203_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
