# Generated by Django 3.0.2 on 2020-03-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0020_auto_20200328_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(),
        ),
    ]
