# Generated by Django 3.0.2 on 2020-03-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0020_remove_book_price'),
        ('details', '0016_remove_book_avg_rating'),
    ]

    operations = [
    ]
