# Generated by Django 3.0.2 on 2020-03-28 22:19

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0021_auto_20200328_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'synopsis', 'ISBN']),
        ),
    ]
