# Generated by Django 3.0.2 on 2020-04-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0026_auto_20200411_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
