# Generated by Django 3.0.2 on 2020-04-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0027_auto_20200411_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
