# Generated by Django 3.0.2 on 2020-04-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekprofile', '0004_auto_20200301_1108'),
        ('Shopping_cart', '0004_auto_20200410_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geekprofile.Profile'),
        ),
    ]
