# Generated by Django 3.0.2 on 2020-04-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart', '0005_auto_20200410_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_ordered',
            new_name='ordered',
        ),
    ]
