# Generated by Django 3.0.2 on 2020-04-10 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0025_auto_20200328_2301'),
        ('Shopping_cart', '0007_auto_20200410_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Book'),
        ),
    ]
