# Generated by Django 3.0.2 on 2020-04-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart', '0008_auto_20200410_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
