# Generated by Django 3.0.2 on 2020-04-10 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0025_auto_20200328_2301'),
        ('Shopping_cart', '0009_auto_20200410_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='details.Book'),
        ),
    ]
