# Generated by Django 3.0.2 on 2020-04-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekprofile', '0004_auto_20200301_1108'),
        ('details', '0025_auto_20200328_2301'),
        ('Shopping_cart', '0011_auto_20200411_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geekprofile.Profile'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Book'),
        ),
    ]
