# Generated by Django 3.0.2 on 2020-04-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart', '0017_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
