# Generated by Django 3.0.2 on 2020-04-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart', '0024_auto_20200411_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quant_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
