# Generated by Django 3.0.2 on 2020-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart', '0025_auto_20200411_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
