# Generated by Django 3.0.2 on 2020-04-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart', '0026_order_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
    ]
