# Generated by Django 3.0.2 on 2020-04-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart', '0027_remove_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_count',
        ),
    ]
