# Generated by Django 3.0.2 on 2020-04-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_cart', '0028_remove_order_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quant_flag',
        ),
    ]
