# Generated by Django 3.0.3 on 2020-02-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekprofile', '0002_auto_20200211_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
