# Generated by Django 3.0.2 on 2020-04-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekprofile', '0004_auto_20200301_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creditcard',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('shipping', 'shipping')], default='home', max_length=8),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geekprofile.Profile'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=19),
        ),
    ]
