# Generated by Django 3.0.3 on 2020-03-05 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekprofile', '0004_auto_20200301_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creditcard',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='geekprofile.CreditCard'),
        ),
    ]
