# Generated by Django 3.0.3 on 2020-03-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekprofile', '0005_auto_20200304_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creditcard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geekprofile.CreditCard'),
        ),
    ]
