# Generated by Django 3.0.3 on 2020-04-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekprofile', '0006_auto_20200305_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('shipping', 'shipping')], default='home', max_length=8),
        ),
    ]
