# Generated by Django 3.0.3 on 2020-04-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geekprofile', '0007_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creditcard',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geekprofile.Profile'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=19),
        ),
    ]
